# PowerAPI CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      # Language image for build and unit tests
      - image: circleci/python:3.7

      # Service image for integration tests
      - image: circleci/mongo:4.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "setup.cfg" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -e ".[mongodb]"

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "setup.cfg" }}

      # Run unit and integration tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python setup.py test
            
  publish-release:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout

      - run:
          name: create venv and verify git tag vs. version
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install --upgrade twine
            python setup.py verify

      - run:
          name: generate package and upload it
          command: |
            python3 setup.py sdist bdist_wheel
            . venv/bin/activate
            twine upload -u powerapi -p $PYPI_PASSWORD dist/* 
        


workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              ignore: /v.*/
      - publish-release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
