name: Build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-and-test:
    name: Build project and run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.x"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[devel]"

    - name: Lint with flake8
      run: |
        flake8 --count --show-source --statistics src/ tests/

    - name: Static code analysis with pylint
      run: |
        pylint src/ tests/

    - name: Test with pytest
      run: |
        pytest --cov=powerapi --cov-report=term --cov-report=xml tests/unit

    - name: Upload coverage reports to Codecov
      if: ${{ matrix.python-version }} == "3.8"
      uses: codecov/codecov-action@ab904c41d6ece82784817410c45d8b8c02684457 # v3.1.6
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage.xml
