name: Build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  build-and-test:
    name: Build project and run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.x"]

    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[devel]"

    - name: Lint with flake8
      run: |
        flake8 --count --show-source --statistics src/ tests/

    - name: Static code analysis with pylint
      run: |
        pylint src/ tests/

    - name: Test with pytest
      run: |
        pytest --cov=powerapi --cov-report=term --cov-report=xml tests/unit

    - name: Upload coverage reports to Codecov
      if: ${{ matrix.python-version }} == "3.8"
      uses: codecov/codecov-action@e0b68c6749509c5f83f984dd99a76a1c1a231044 # v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage.xml

  build-container-image:
    name: Build container image
    runs-on: ubuntu-latest

    steps:
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Build image
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0
        with:
          push: false
          provenance: false
          tags: localbuild/powerapi:sha-${{ github.sha }}
