name: CI

on: [push, pull_request]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
      influx:
        image: influxdb:1.8
        ports:
          - 8086:8086
    steps:
      - name: install environment
        run: |
          sudo apt-get update
          sudo apt install -y libvirt-dev
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('powerapi/__init__.json') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pylint
          pip3 install -e ".[mongodb, influxdb, prometheus, libvirt]"
      - name: Test with pytest
        run: python3 setup.py test
      - name: lint with flake8
        run: flake8 powerapi
