name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  pre-checks:
    name: Release Pre-Checks
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: Check if package version corresponds to git tag
      shell: python
      env:
        PYTHONPATH: ${{ github.workspace }}/src
      run: |
        import os
        import sys
        from powerapi import __version__

        git_tag = os.environ['GITHUB_REF_NAME'].removeprefix('v')
        pkg_version = __version__

        if git_tag != pkg_version:
          title = 'Invalid version'
          file = 'src/powerapi/__init__.py'
          msg = f'Version mismatch between python package ({pkg_version}) and git tag ({git_tag})'
          print(f'::error title={title},file={file}::{msg}')
          sys.exit(1)

  pypi-package:
    name: Publish Pypi package
    runs-on: ubuntu-latest
    needs: pre-checks
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: Set up Python
      uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package
      run: python -m build

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@ec4db0b4ddc65acdf4bff5fa45ac92d78b56bdf0 # v1.9.0
      with:
        print-hash: true

  docker-image:
    name: Publish Docker image
    runs-on: ubuntu-latest
    needs: pre-checks
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@5927c834f5b4fdf503fca6f4c7eccda82949e1ee # v3.1.0

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@4fd812986e6c8c2a69e18311145f9371337f27d4 # v3.4.0

      - name: Log in to Docker Hub
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
        with:
          images: |
            docker.io/powerapi/powerapi
            ghcr.io/powerapi-ng/powerapi
          tags: |
            type=pep440,pattern={{version}}

      - name: Build and push Docker image
        uses: docker/build-push-action@a254f8ca60a858f3136a2f1f23a60969f2c402dd # v6.4.0
        id: build-and-push
        with:
          push: true
          provenance: false
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  github-release:
    name: Publish GitHub release
    runs-on: ubuntu-latest
    needs: [pre-checks, pypi-package, docker-image]
    permissions:
      contents: write
    env:
      CHGLOG_VERSION: "0.15.4"

    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        fetch-depth: 0

    - name: Generate version changelog
      run: |
        set -euo pipefail
        export BASE_URL="https://github.com/git-chglog/git-chglog/releases/download"
        export FILENAME="git-chglog_${CHGLOG_VERSION}_linux_amd64.tar.gz"
        curl -fsSL "${BASE_URL}/v${CHGLOG_VERSION}/${FILENAME}" |sudo tar xz --no-same-owner -C /usr/local/bin git-chglog
        git-chglog --config .github/chglog/config.yml --output CHANGELOG.md "${GITHUB_REF_NAME}"

    - name: Create GitHub release
      uses: softprops/action-gh-release@a74c6b72af54cfa997e81df42d94703d6313a2d0 # v2.0.6
      with:
        body_path: CHANGELOG.md
